version: "3.7"

services:
  mister-build:
    build: .
    volumes:
      - ./Linux-Kernel_MiSTer:/mister
    environment:
        ARCH: arm
        CROSS_COMPILE: /opt/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
